
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: '0.6.6'
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install project
        run: uv run pip install -e .

      - name: Build
        uses: docker://ghcr.io/atopile/atopile-kicad:main
        id: build
        continue-on-error: true

      - name: Upload Combined Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

      - name: Check build status
        if: steps.build.outcome == 'failure'
        run: exit 1